nodeLinker: node-modules

packageExtensions:
  "@medusajs/cli@*":
    dependencies:
      tsconfig-paths: "^4.2.0"
  "@medusajs/core-flows@*":
    dependencies:
      "@medusajs/workflows-sdk": "2.13.1"
  "@medusajs/framework@*":
    dependencies:
      ioredis: "^5.4.1"
      zod: "3.25.76"
